export const seoPages: Record<string,{title:string;description:string;heading:string;paragraphs:string[]}> = {
  "custom-cookies": {title:"Custom Cookies in Glenpool, Oklahoma",description:"Handcrafted custom cookies for celebrations, gifts, and special events in Glenpool, Oklahoma.",heading:"Custom Cookies Made for Your Celebration",paragraphs:["Every custom order begins with your occasion, preferred colors, theme, names, dates, and important details.","Poppy creates each collection by hand so it feels personal, coordinated, and memorable."]},
  "decorated-sugar-cookies": {title:"Decorated Sugar Cookies",description:"Detailed decorated sugar cookies handcrafted for celebrations, gifts, weddings, birthdays, and showers.",heading:"Handcrafted Decorated Sugar Cookies",paragraphs:["Beautiful sugar cookies bring together careful baking, detailed icing, and coordinated colors.","They work well as party favors, dessert-table accents, and thoughtful gifts."]},
  "birthday-cookies": {title:"Custom Birthday Cookies",description:"Personalized birthday cookies designed around favorite colors, names, themes, and milestone ages.",heading:"Custom Birthday Cookies for Every Age",paragraphs:["Make a birthday more personal with cookies designed around the guest of honor.","Collections can feature names, ages, hobbies, favorite colors, and party themes."]},
  "wedding-cookies": {title:"Custom Wedding Cookies",description:"Elegant wedding cookies for receptions, rehearsal dinners, engagements, anniversaries, and favors.",heading:"Wedding Cookies Designed for Your Special Day",paragraphs:["Wedding cookies add a coordinated personal detail to receptions and related celebrations.","Designs may be inspired by colors, flowers, initials, invitations, or the venue."]},
  "baby-shower-cookies": {title:"Custom Baby Shower Cookies",description:"Sweet custom baby shower cookies for welcoming a new arrival and celebrating growing families.",heading:"Baby Shower Cookies for a Sweet Welcome",paragraphs:["Celebrate a new arrival with cookies created around the shower colors and theme.","Collections can include names, initials, florals, animals, and storybook inspiration."]},
  "bridal-shower-cookies": {title:"Custom Bridal Shower Cookies",description:"Elegant bridal shower cookies for showers, engagements, bridesmaid gifts, and wedding events.",heading:"Elegant Bridal Shower Cookies",paragraphs:["Bridal shower cookies coordinate desserts and favors with the bride's celebration.","Florals, rings, bows, initials, and wedding colors can inspire the collection."]},
  "holiday-cookies": {title:"Custom Holiday Cookies",description:"Handcrafted holiday cookies for family parties, workplace celebrations, gifts, and seasonal events.",heading:"Handcrafted Cookies for Holiday Celebrations",paragraphs:["Seasonal cookies add a festive detail to gatherings and gift exchanges.","Sets make thoughtful gifts for hosts, teachers, neighbors, coworkers, and family."]},
  "corporate-business-cookies": {title:"Corporate and Business Cookies",description:"Custom business cookies for clients, employees, openings, company events, and appreciation gifts.",heading:"Custom Cookies for Businesses",paragraphs:["Business collections help recognize employees, welcome customers, and celebrate milestones.","They can reflect company colors, event themes, openings, and appreciation campaigns."]},
  "custom-cookie-orders": {title:"How to Order Custom Cookies",description:"Learn how to select cookies, provide event details, review notes, and complete secure checkout.",heading:"How to Place a Custom Cookie Order",paragraphs:["Choose a product and variation, then add names, dates, colors, themes, and instructions.","Review each item and note before choosing pickup or eligible shipping and continuing to Square."]},
  "cookie-gift-sets": {title:"Custom Cookie Gift Sets",description:"Handcrafted gift sets for birthdays, holidays, appreciation, celebrations, and meaningful gifts.",heading:"Custom Cookie Gift Sets",paragraphs:["A coordinated cookie set is a personal way to celebrate, congratulate, or thank someone.","Sets can reflect the recipient's interests, colors, profession, or special occasion."]},
  "special-event-cookies": {title:"Special Event Cookies",description:"Decorated cookies for graduations, retirements, anniversaries, reunions, parties, and events.",heading:"Custom Cookies for Special Events",paragraphs:["Custom cookies connect the dessert table with the story of an important event.","Share the event type, colors, date, wording, and inspiration when ordering."]},
};
